USE SCHEMA LANDING;

CREATE OR REPLACE FILE FORMAT ABC_BANK_CSV_FILE_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
    TRIM_SPACE = FALSE
    ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE
    ESCAPE = 'NONE'
    ESCAPE_UNENCLOSED_FIELD = '\134'
    DATE_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    NULL_IF = ('\\N');

CREATE OR REPLACE TABLE ABC_BANK_POSITION (
    accountID TEXT,
    symbol TEXT,
    description TEXT,
    exchange TEXT,
    report_date DATE,
    quantity NUMBER(38, 0),
    cost_base NUMBER(38, 5),
    position_value NUMBER(38, 5),
    currency TEXT
)
STAGE_FILE_FORMAT = ABC_BANK_CSV_FILE_FORMAT;

PUT 'file://${projectDirectory}/data/ABC_Bank_PORTFOLIO__2021-04-09.csv' @%ABC_BANK_POSITION;
COPY INTO ABC_BANK_POSITION;


