WITH
CURRENT_FROM_SNAPSHOT AS (
    SELECT
        *
    FROM {{ ref('SNSH_COUNTRY_INFO')}}
    WHERE DBT_VALID_TO IS NULL
)
SELECT
    * EXCLUDE (DBT_SCD_ID, DBT_UPDATED_AT, DBT_VALID_FROM, DBT_VALID_TO)
FROM CURRENT_FROM_SNAPSHOT