SELECT
    TWO_COUNTRY_CODE,
    THREE_COUNTRY_CODE,
    COUNTRY_NAME,
    REGION_NAME,
    SUB_REGION_NAME,
    LOAD_TS_UTC,
    COUNTRY_HKEY,
    COUNTRY_HDIFF,
    RECORD_SOURCE
FROM {{ ref('REF_COUNTRY_INFO') }}