SELECT
    CURRENCY_CODE,
    CURRENCY_NAME,
    CURRENCY_SYMBOL,
    OWNING_COUNTRY_CODE,
    LOAD_TS_UTC,
    CURRENCY_HKEY,
    CURRENCY_HDIFF,
    RECORD_SOURCE
FROM {{ ref('REF_CURRENCY_INFO') }}