SELECT
    SECURITY_CODE,
    SECURITY_NAME,
    SECTOR_NAME,
    INDUSTRY_NAME,
    COUNTRY_CODE,
    EXCHANGE_CODE,
    LOAD_TS_UTC,
    SECURITY_HKEY,
    SECURITY_HDIFF,
    RECORD_SOURCE
FROM {{ ref('REF_SECURITY_INFO_ABC_BANK') }}