SELECT
    ACCOUNT_CODE,
    SECURITY_CODE,
    SECURITY_NAME,
    EXCHANGE_CODE,
    REPORT_DATE,
    QUANTITY,
    COST_BASE,
    POSITION_VALUE,
    CURRENCY_CODE,
    UNREALIZED_PROFIT,
    UNREALIZED_PROFIT_PCT
FROM {{ ref('REF_POSITION_ABC_BANK') }}